### ISSUE TITLE
Wrong result (Need to output the entire array with the changed values)

### ISSUE THREAD

**Issue by Kashoid23** [KateHaman/RubyHM#1]
Instead of

```
irb(main):012:0> arr = [2, 3, 4, 5, 6, 7]
=> [2, 3, 4, 5, 6, 7]
irb(main):013:0> (arr[1..-2].select.with_index{|n, idx| n.even?}).map {|a| arr[0]+a}
=> [6, 8]
```

Should be

`=> [2, 3, 6, 5, 8, 7]`

https://github.com/KateHaman/RubyHM/blob/3ace5000a5fcdf0aed6acfb09773390aa30423e5/HW1/tasks.rb#L19
https://github.com/KateHaman/RubyHM/blob/3ace5000a5fcdf0aed6acfb09773390aa30423e5/HW1/tasks.rb#L23
https://github.com/KateHaman/RubyHM/blob/3ace5000a5fcdf0aed6acfb09773390aa30423e5/HW1/tasks.rb#L27
https://github.com/KateHaman/RubyHM/blob/3ace5000a5fcdf0aed6acfb09773390aa30423e5/HW1/tasks.rb#L31

**Comment by Kashoid23** [comment]
@KateHaman Hi!

These two will return an incorrect result.
We discussed one of them at a lecture.
If the first two elements will be even/odd
FE: array = [2, 2, 3, 4, 5, 6, 7]
they will not be executed for the first even/odd element after the first element of the array.

```
puts '5. Дан целочисленный массив. Преобразовать его, прибавив к четным числам первый элемент. Первый и последний элементы массива не изменять.'
array = [2, 3, 4, 5, 6, 7]
array.map {|element| element.even? && (element != array[0] && element != array[-1]) ? element + array.first : element}
```

```
puts '7. Дан целочисленный массив. Преобразовать его, прибавив к нечетным числам последний элемент. Первый и последний элементы массива не изменять.'
array = [2, 3, 4, 5, 6, 7]
array.map {|element| element.odd? && (element != array[0] && element != array[-1]) ? element + array.last : element}
```

**Comment by amin1419** [comment]
#5
