### ISSUE TITLE
We need scopes

### ISSUE THREAD

**Issue by Kashoid23** [KateHaman/RubyHM#17]
6) ... используйте scope (:published) отсеивая только опубликованные комментарии с помощью выборки

but instead of zero you can use enum directly, fe:
`scope :published, -> { where(status: :published) }`

https://github.com/KateHaman/RubyHM/blob/91704733d81766ed33ba14a20d27512109bfa6b6/Blog/app/models/comment.rb#L13

**Comment by KateHaman** [comment]
applied the changes, thanks. Still have one question left. When I have commented the scopes lines, nothing changed and everything worked as expected. Could it be that when enum is used, the scopes are somehow defined by default?
